There is a 400 HTTP error when loading the list of preset sounds because they don't exist. Is it possible to remove the preset sounds since those were just hardcoded previously? The real sounds are coming from the sounds API. The error stack trace is listed below:
Error: Post loadAudio: HTTP error! status: 400 for URL https://6000-idx-studio-1745637975998.cluster-fnjdffmttjhy2qqdugh3yehhs2.cloudworkstations.dev/sounds/preset-lead-1.wav
    at createUnhandledError (https://6000-idx-studio-1745637975998.cluster-fnjdffmttjhy2qqdugh3yehhs2.cloudworkstations.dev/_next/static/chunks/node_modules_next_dist_client_43e3ffb8._.js:879:71)
    at handleClientError (https://6000-idx-studio-1745637975998.cluster-fnjdffmttjhy2qqdugh3yehhs2.cloudworkstations.dev/_next/static/chunks/node_modules_next_dist_client_43e3ffb8._.js:1052:56)
    at console.error (https://6000-idx-studio-1745637975998.cluster-fnjdffmttjhy2qqdugh3yehhs2.cloudworkstations.dev/_next/static/chunks/node_modules_next_dist_client_43e3ffb8._.js:1191:56)
    at FragmentPost.useCallback[loadAudio] (https://6000-idx-studio-1745637975998.cluster-fnjdffmttjhy2qqdugh3yehhs2.cloudworkstations.dev/_next/static/chunks/src_04efae72._.js:3358:29)